## Exercise 43 - Writing Files

# Write a program that creates two different files.
# The first file should be opened normally and two lines should be written in it.
# Afterwards close the file, open it again and add another three lines of text to the file
# The second file should be generated by using „with“ and a loop to write a countdown from 10 to 0
# Each number should be in a separate line
import os.path
from os import path

file1 = open("First_File.txt", "w")
file1.write("This is the first file for exercise 43. \n")
file1.write("This is the second line. \n")
file1.close()

file1 = open("First_File.txt", "a")
file1.write("Line 3. \nLine 4. \nLine 5.\n")

with open("Second_File.txt", "w") as file2:
    file2.write(f"Start the countdown!\n")
    for i in range(11):
        file2.write(f"{10-i}\n")


## Exercise 44 - Reading a file

# Read in your second file from exercise 43, the one with the countdown, by using the generator method
# Calculate the sum of the numbers and print out the result

with open("Second_File.txt", "r") as file2:
    sum = 0
    for line in file2:
        if line.strip("\n").isdigit():
            sum += int(line)

print(f"The sum of all numbers in the file is {sum}")


# Exercise 45 - Copying files

# Write a program that takes the name of a file from the user and generates a copy of this file
# The Copy should be generated by writing the contents of the original file into a new file line by line
# Use generators to optimize your memory usage for this exercise

user_input = input("Which file do you want to copy? \n")

if path.exists(user_input):
    file_name = user_input.split(".")
    with open(f"{file_name[0]}(copy).{file_name[1]}", "w") as copy_file: 
        with open(user_input, "r") as file:
            for line in file:
                copy_file.write(line)

else:
    print("This file does not exist.")
